### ISSUE TITLE
StationBoard Response Error

### ISSUE THREAD

**Issue by ArminGe** [MrKrisKrisu/hafas-client-php#1]
With PHP 8.1 I get with some requests (not all) the following error:

Fatal error: Uncaught TypeError: HafasClient\Models\Operator::__construct(): Argument #1 ($id) must be of type string, null given, called in /var/www/html/vendor/traewelling/hafas-client-php/src/Response/StationBoardResponse.php on line 56 and defined in /var/www/html/vendor/traewelling/hafas-client-php/src/Models/Operator.php:14 Stack trace: #0 /var/www/html/vendor/traewelling/hafas-client-php/src/Response/StationBoardResponse.php(56): HafasClient\Models\Operator->__construct(NULL, NULL) #1 /var/www/html/vendor/traewelling/hafas-client-php/src/Hafas.php(56): HafasClient\Response\StationBoardResponse->parse() #2 /var/www/html/views/poi.php(94).

I bypassed that by changing the operator.php :

`<?php

namespace HafasClient\Models;

/**
 * @package HafasClient\Models
 * @todo    make readonly
 */
class Operator {

    public ?string  $id; /* add question mark
    public ?string $name;

    public function __construct(string $id = null, string $name = null) {    */add = null to $id
        $this->id   = $id;
        $this->name = $name;
    }

    public function __toString(): string {
        return json_encode([
                               'type' => 'operator',
                               'id'   => $this->id,
                               'name' => $this->name,
                           ]);
    }
}`

**Comment by MrKrisKrisu** [comment]
I can't find any error on connections I tested. It looks like an operator is missing in the response. Can you tell me the request (incl. stop, date + time) you used so I can reproduce the request?

**Comment by MrKrisKrisu** [comment]
I took the opportunity to write a few simple tests: https://github.com/MrKrisKrisu/hafas-client-php/pull/2

**Comment by ArminGe** [comment]
For example on this `request:

` $data = Hafas::getDepartures(
                    lid: 590324,
                    timestamp: Carbon::now(+1),
                    maxJourneys: 10,
                    filter: new ProductFilter(
                        nationalExpress: true,
                        national: true,
                        regionalExp: true,
                        regional: true,
                        suburban: true,
                        bus: true,
                        ferry: false,
                        subway: true,
                        tram: true,
                        taxi: false,

                    )
                );`

**Comment by MrKrisKrisu** [comment]
The problem was that HAFAS doesn't know the operators from lines at the station "Geigenbauschule, Mittenwald".
fixed in v0.5.
